#!/bin/bash
VERSION=0.1.1
rm make_download make_build make_prepare
if [ ! -d tmp ];then mkdir tmp;fi

for fmt in alaw g722 g729 gsm opus sln16 ulaw wav siren7 siren14; do
if [ ! -f tmp/asterisk-core-sounds-cs-${fmt}-ladislav-v${VERSION}.tar.gz ];then wget -P tmp https://github.com/misak0007/asterisk-core-sounds-cs/releases/download/v${VERSION}/asterisk-core-sounds-cs-${fmt}-ladislav-v${VERSION}.tar.gz;fi
suma=$(sha256sum tmp/asterisk-core-sounds-cs-${fmt}-ladislav-v${VERSION}.tar.gz | cut -d" " -f1)
cat <<EOF >> make_download
ifneq (\$(CONFIG_PACKAGE_asterisk-core-sounds-cs-${fmt}-ladislav)\$(CONFIG_PACKAGE_asterisk-core-sounds-voicemail-cs-${fmt}-ladislav),)
\$(eval \$(call Download,asterisk-sound,asterisk-core-sounds-cs-${fmt}-ladislav-v\$(PKG_VERSION),${suma}))
endif
EOF
cat <<EOF >> make_build
\$(eval \$(call BuildasteriskCoreSound,${fmt},Csech core sound Files. ${fmt} format,ladislav))
\$(eval \$(call BuildasteriskCoreSoundVoicemail,${fmt},Csech core sound voicemail Files. ${fmt} format,ladislav))
EOF
cat <<EOF >> make_prepare
ifneq (\$(CONFIG_PACKAGE_asterisk-core-sounds-cs-${fmt}-ladislav)\$(CONFIG_PACKAGE_asterisk-core-sounds-voicemail-cs-${fmt}-ladislav),)
	\$(HOST_TAR) -C \$(PKG_BUILD_DIR)/core-cs -xzf \$(DL_DIR)/asterisk-core-sounds-cs-${fmt}-ladislav-v\$(PKG_VERSION).tar.gz
endif
EOF
done

cat Makefile.stage1 > Makefile
cat make_download >> Makefile
cat Makefile.stage2 >> Makefile
cat make_prepare >> Makefile
cat Makefile.stage3 >> Makefile
cat make_build >> Makefile
sed -i "s/@VERSION@/${VERSION}/g" Makefile
